### ISSUE TITLE
automatic system update failed

### ISSUE THREAD

**Issue by moritzthecat** [roobbb/owserver#4]
this is not the issue as upgrade has been done a year ago - mixing 2022 with 2023 .
sorry for confusion. need to check elsewhere.

**Comment by roobbb** [comment]
Hello.

No problem at all 🙂
Updates get usually rolled out by new docker container versions, so you can pull the latest (manually or even by Watchtower as described in my Wiki). 
In this case I didn't perform updates for a long time, because there were no big/ important security updates in the base image or in the owserver packages and I do not have any Denkovi hardware anymore.

I have pushed an updated container version on dockerhub right now. Please let me know if it works after pulling this latest version.

Thank you and kind regards
roobbb
